global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Apex-Migrations Lab'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  ###########
  # Traefik #
  ###########
  # Collects Traefik Metrics configured in the static traefik configuration
  - job_name: traefik
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.3:8082']

  ##############
  # Prometheus #
  ##############
  # Collects metrics about Prometheus
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.2.3:9090']

  #################
  # node_explorer #
  #################
  # Collects metrics about Prometheus
  - job_name: 'oppervlakpro3'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.2.3:49664']
 
  ############
  # Cadvisor #
  ############
  # Collects info based on Cadvisor for containers
  - job_name: grafana.cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana.cadvisor:8080']

  #################
  # Node-Exporter #
  #################
  # Collects info based on the node exporer
  - job_name: grafana.node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana.node-exporter:9100']

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091
#     static_configs:
#          - targets: ['node-exporter:9100']