server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://grafana.loki:3100/api/v1/push

scrape_configs:
 - job_name: system
   static_configs:
   - targets:
      - server17a
     labels:
        job: traefik
        __path__: /logs/access.log