server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: traefik_log
  static_configs:
  - targets:
      - loki
    labels:
      job: traefik_logs
      __path__: /logs/access.log

  - targets:
      - loki
    labels:
      job: traefik.logs
      __path__: /logs/traefik.log

  # Nextcloud promtail setup
  - targets:
      - loki
    labels:
      instance: server17a #hostname -f
      env: docker #Environment label
      job: nextcloud.logs #job label
      __path__: /home/gregory/srv/nextcloud/nextcloud/data/{audit,nextcloud}.log #path